name = "wtm-analytics"
main = "src/index.js"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
	{ binding = "WTM_USER_TESTING", id = "37bd29e5fd0d47ed8a1a4358c52c758c" }
]
